# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to gh-pages

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
       
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn install
    - run: yarn build
    - run: yarn test

    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.2.0
      with:
        fqdn: sz-rat.zsh2401.top
        build_dir: ./dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    env:
      CI: true